config/routes.rb
Rails.application.routes.draw do
  resources :connpass
  root to: 'connpass#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/connpass_controller.rb
class ConnpassController < ApplicationController
  include ConnpassHelper

  def index
    connpass_research(params[:keyword]) if params[:keyword]
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def top
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connpass_helper.rb
module ConnpassHelper

  def connpass_research(keyword)
    uri = URI.parse("https://connpass.com/api/v1/event/?keyword=#{keyword}")
    json = Net::HTTP.get(uri)
    @results = JSON.parse(json)
  end

  def result_event_links_path
    if @results
      'connpass/index/index_result'
    else
      'connpass/index/non_index_result'
    end
  end

end

app/views/connpass/edit.html.erb
<h1>Connpass#edit</h1>
<p>Find me in app/views/connpass/edit.html.erb</p>

app/views/connpass/index.html.erb
<h1>Connpass#index</h1>
<%= render 'connpass/index/index_search' %>
<%= render result_event_links_path %>

app/views/connpass/index/_index_result.html.erb
<% @results["events"].each do |result| %>
  <p><%= result["title"] %></p>
<% end %>

app/views/connpass/index/_index_search.html.erb
<%= form_tag(connpass_index_path, method: 'get') do %>
  <%= text_field_tag :keyword %>
  <%= submit_tag '検索' %>
<% end %>

app/views/connpass/index/_non_index_result.html.erb
<p>検索ワードを入力してください</p>
<p>
  <small>（例）Ruby Java Python PHP AWS</small>
</p>

app/views/connpass/new.html.erb
<h1>Connpass#new</h1>
<p>Find me in app/views/connpass/new.html.erb</p>

app/views/connpass/show.html.erb
<h1>Connpass#show</h1>
<p>Find me in app/views/connpass/show.html.erb</p>

app/views/connpass/top.html.erb
<h1>Connpass#top</h1>
<p>Find me in app/views/connpass/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiSample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>